TWILIO_ACCOUNT_SID=AC4b88cb0f2e33a7f05ee5498294e3a86c
TWILIO_AUTH_TOKEN=3ea0944a305dec619c46db9738f8dd67
TWILIO_PHONE_NUMBER=+14646668557
SERVER_URL="SERVER_URL=https://safetrack.streamlit.app
DATABASE_URL = "sqlite:///safetrack.db"
